name: Multiple-Jobs Sample

on:
    push:
        branches:
            - main

jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run build
              run: ./create-dummy-file.sh
              working-directory: scripts
