name: Jobs Lab

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building..."
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing after build"
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Linting in parallel"