name: Jobs-Labb

on: [push]

jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - run: echo "Building..."
  test:
    needs: build
    runs-on: arc-runner-set
    steps:
      - run: echo "Testing after build"
  lint:
    runs-on: arc-runner-set
    steps:
      - run: echo "Linting in parallel"
